import {chromium} from '/opt/node-tools/node_modules/playwright/index.mjs';
import fs from 'fs';import http from 'http';import path from 'path';
const dir=path.dirname(new URL(import.meta.url).pathname),root=path.resolve(dir,'../..');
const srv=http.createServer((q,r)=>{const f=path.join(root,decodeURIComponent(q.url.split('?')[0]));try{const b=fs.readFileSync(f.endsWith('/')?f+'index.html':f);r.writeHead(200,{'content-type':f.endsWith('.js')?'text/javascript':'text/html; charset=utf-8'});r.end(b)}catch(e){r.writeHead(404);r.end()}}).listen(8765);
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'}).catch(()=>chromium.launch());
const pg=await b.newPage();const errs=[];pg.on('pageerror',e=>errs.push(e.message));
await pg.goto('http://localhost:8765/pm/index.html');await pg.waitForTimeout(800);
await pg.addScriptTag({content:fs.readFileSync(dir+'/seed.js','utf8')});
const out=await pg.evaluate(L=>seed(L),fs.readFileSync(dir+'/logo.svg','utf8'));
fs.writeFileSync(dir+'/AEROVA-demo-company.json',JSON.stringify(out));
console.log('errors',errs, 'size',JSON.stringify(out).length, Object.values(out.projects).map(p=>p.name), out.co.staff.length);
await b.close();srv.close();
